SELECT EQNUMB, EQNAME, DEPT, CAPACITY, RATING,WEIGHT, DATEINST,MFR,MODEL,VENDOR,SERIALNUMB,MFRPHONE,EQLOC,VENDNAME,
CONTACT,PHONE,ACCOUNT,MASTEREQ,SITE,ADDRESS,EQSUPVISOR,NEWEQFIELD1,NEWEQFIELD2,NEWEQFIELD3,NEWEQFIELD4,NEWEQFIELD5,
NEWEQFIELD6,NEWEQFIELD7,NEWEQFIELD8,NEWEQFIELD9,NEWEQFIELD10,NEWHAFIELD08, NEWHAFIELD24 ,
NEWHAFIELD25, NEWHAFIELD26, NEWHAFIELD30, EQCLASS,EQSYSTEM,TANKLEVEL1,TANKLEVEL2 FROM EQREC
